### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by widepeepoclap** [davidzeng0/yasha#5]
After a few days of playing audio files, it seems like the memory isn't getting released back to the system at all. The rss value increases over time and never goes down.

Things I tried while debugging:
- Waiting for the garbage collector to kick in.
- Using the --expose-gc flag and calling global.gc() after destroying the player.
- Using the example code to make sure it's not an issue with my code.

This also seems to be happening with EarTensifier bot as the rss is 2x the heapUsed which is a lot compared to the initial boot values.

**Comment by davidzeng0** [comment]
This is a problem with FFmpeg, not a problem with my code. If you are calling destroy player, then all resources are freed. What's happening here is FFmpeg's very memory allocation heavy code and that the operating system isn't reclaiming the memory due to laziness. 

Edit: grammar

**Comment by davidzeng0** [comment]
I've done tests where I've launched several thousand players, killed them, and relaunched them, and the memory stays high but doesn't get higher, and after 10 minutes the memory usage stops growing.

**Comment by widepeepoclap** [comment]
Is there any workaround? Does using a different malloc help in this case?

**Comment by davidzeng0** [comment]
I don't know if you can configure FFmpeg's malloc, I haven't gone through their source code that much, but the issue seems to be their libavformat library.

**Comment by davidzeng0** [comment]
There are other forums that mention this "leak" and named possible causes like heap fragmentation, but I haven't bothered too much investigating.

**Comment by widepeepoclap** [comment]
I'd love to help with this but I don't have any experience with cpp yet.
A cron restart wouldn't hurt anyways. Thanks for the help.

**Comment by davidzeng0** [comment]
I have a newer project coming out in about 1-2 months to replace this library and it doesn't have this issue. Can't give any promises on actual release date. Also uses 92% less cpu and 115KiB of memory per player on average. That's all I can promise as of now. Also, if you have more memory than it uses RSS, I think you'll be fine even without restarts.

**Comment by widepeepoclap** [comment]
Sounds really promising! Too good to be true actually 😅 since you've already did an amazing job on this and sange. Will be looking forward to try it though!

**Comment by davidzeng0** [comment]
Hey, don't know if you're going to see this but the project has taken significantly longer than I anticipated.
I felt like I should inform you on the progress I've made since:
I think I might have some kind of prototype soon (<1 month away). I've already released most of the code that I've written so far in

[xe](https://github.com/ilikdoge/xe)
[xetrov](https://github.com/ilikdoge/xetrov)

and so far it covers all the basic needs of the final project

Though I am somewhat concerned about the safety of the code as I have not had time to check all my code logic.
If everything goes well, I should have something good before the end of the year :)
